name: sh-checker
on:
  - pull_request
  - commit
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC1004 # It is posible to exclude some shellcheck warnings.
          SHFMT_OPTS: -ci -sr -i 0 # It is posible to pass arguments to shftm
        with:
          sh_checker_comment: true
